mutation dossierModifierAnnotationText($input: DossierModifierAnnotationTextInput!) {
	dossierModifierAnnotationText(input: $input) {
		annotation {
			id
			stringValue
		}
		errors {
			message
		}
	}
}