query getDemarche(
	$demarcheNumber: Int!	
) {
	demarche(number: $demarcheNumber) {
		activeRevision {
			id
			dateCreation
			champDescriptors {
				id
				label
				type
			}
			annotationDescriptors {
				id
				label
				type
			}
		}
		state
	}
}